version: '3.7'

services:

  spring-api-db:
    image: mysql
    container_name: spring-api-db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - spring-api-db:/var/lib/mysql
    networks:
      - spring-api-network

  spring-api:
    image: thisk8brd/spring-api
    container_name: spring-boot-api
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - spring-api-db
    networks:
      - spring-api-network

volumes:
  spring-api-db:
    name: spring-api-db

networks:
  spring-api-network:
    name: spring-api-network
